services:
  - type: web
    name: exam-tracker
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RECEIVER_EMAIL
        sync: false
      - key: ADMIN_ID
        value: raja
      - key: ADMIN_PASS
        value: 1114@
